### ISSUE TITLE
Allow choosing a revision to request

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-reports#26]
Right now, we show the latest build. We should allow the user to choose a different revision.

**Comment by abhiaecs** [comment]
Hey!
I'm interested in working on this!
Can you help me get started in setting up env and explaining the problem statement?

**Comment by abhiaecs** [comment]
Yep! They are working fine for me in Firefox 62.

**Comment by marco-c** [comment]
Nice! So now you could start implementing this. You'll need to change the functions that are requesting data from the coverage backend (https://github.com/marco-c/code-coverage-reports/blob/51026a70697c1a78d571e3a2deca652f83419555/common.js#L33) to also use a revision parameter, then you'll need to change report.html to add a field (for now a small text input field) where a user can write a custom revision and then change report.js to take this revision into account (always using the latest revision when the field is empty, and the revision from the field when it is not empty).

**Comment by marco-c** [comment]
COVERAGE_BACKEND_HOST is the coverage service, we don't have to change that. We have to change the functions just after that to accept a `revision` parameter and use it.

**Comment by twisted-sres** [comment]
Hey, I am a complete beginner, can I take up this issue as my first issue?

**Comment by marco-c** [comment]
Sure, no need to ask, you can submit a PR when you have a fix. Issues are assigned when there is a PR to fix them.

**Comment by vipulchhabra99** [comment]
hello @marco-c can u please explain what actually i have to do i am unable to understand from previous comments

**Comment by marco-c** [comment]
@vipulchhabra99, https://github.com/marco-c/code-coverage-reports/issues/26#issuecomment-431972338 is the description of what needs to be done. Tell me which part is not clear and I'll clarify.

**Comment by vipulchhabra99** [comment]
@marco-c i mean that we should allow user to choose among different versions of report to be displayed?

**Comment by vipulchhabra99** [comment]
@marco-c  please check my pr request

**Comment by marco-c** [comment]
> @marco-c i mean that we should allow user to choose among different versions of report to be displayed?

Yes, according to the selected revision.

**Comment by vipulchhabra99** [comment]
@marco-c ok great once i read the files properly i would start working

**Comment by vipulchhabra99** [comment]
@marco-c can you please help me with files names which are associated with this issue.

**Comment by marco-c** [comment]
Again, the files are mentioned in https://github.com/marco-c/code-coverage-reports/issues/26#issuecomment-431972338 :smile:

**Comment by vipulchhabra99** [comment]
oh sorry @marco-c i didn't see that .Thanks for help :smile:

**Comment by vipulchhabra99** [comment]
@marco-c i want to know that are different versions maintained on the servers from where the data is being fetched?

**Comment by marco-c** [comment]
Yes @vipulchhabra99, this is all described in that comment. There is a `revision` parameter that the server accepts.

**Comment by vipulchhabra99** [comment]
hey @marco-c i was figuring out how to sort this issue i found a way that i can create a function in same html file and create duplicate report.js with some other name and use a function defined by me instead of latest revision and whenever by revision_phid is mentioned by user then new file would be called else the other file is this approach correct or should i think of some other way?

**Comment by marco-c** [comment]
The report.js file should not be duplicated. In report.html, you'll add a text field to specify the revision to use, and when the user inserts it and press enter, you'll load the specified revision.

**Comment by vipulchhabra99** [comment]
ya but i think there is difference in both the funtions that is used and that need to be used that's why i was thinking this method anyways i will try to complete that part in same file can u please help me for any revision_phid so that i can test my code?

**Comment by vipulchhabra99** [comment]
@marco-c please help me with some value of revision_phid so that i can test my code

**Comment by marco-c** [comment]
You can see some revisions at https://hg.mozilla.org/mozilla-central/pushloghtml (not `revision_phid`, that's unrelated). They are the values in the `Changeset` column.

**Comment by vipulchhabra99** [comment]
Ok thanks @marco-c sorry for mess created by me

**Comment by vipulchhabra99** [comment]
hey @marco-c basically you want to met send revision value to changeset summary function?

**Comment by marco-c** [comment]
@vipulchhabra99 sorry I don't understand your question.

**Comment by vipulchhabra99** [comment]
@marco-c they are different types of options available in swagger Ui so to which I have to send the text input by user ?.I thought it to send it to revision-phid but the log has changed values

**Comment by marco-c** [comment]
@vipulchhabra99 solving issues will need a bit of investigation, if I tell you everything you won't have learned anything and I would have spent the same time as doing it myself :smile:

**Comment by vipulchhabra99** [comment]
Yes you are right @marco-c I will try to fix it soon.

**Comment by vipulchhabra99** [comment]
@marco-c can you please help?

**Comment by dev503-student** [comment]
[Edit]
Please consider the below image which has an updated text box to find the revision number or changeset.

![capture](https://user-images.githubusercontent.com/34271764/51693252-98718a00-2024-11e9-90f4-2286a9ebab33.PNG)

**Comment by marco-c** [comment]
I'm confused about exactly what you are doing.
The objective of this issue is to make it possible for the user to request from the coverage backend a different revision than the latest.
Right now we are always using the latest: https://github.com/marco-c/code-coverage-reports/blob/51026a70697c1a78d571e3a2deca652f83419555/report.js#L68.

**Comment by vipulchhabra99** [comment]
@marco-c what's you IRC I'd I want to discuss something related to it

**Comment by vipulchhabra99** [comment]
I tried changing value of changeset to some other changeset fixed value but the latest was only being fetched

**Comment by marco-c** [comment]
> @marco-c what's you IRC I'd I want to discuss something related to it?

'marco', we can chat about this in the #codecoverage channel.

**Comment by vipulchhabra99** [comment]
@marco-c  sorry,i am unable to find #codecoverage on irc.mozilla.org server

**Comment by dev503-student** [comment]
> I'm confused about exactly what you are doing.
> The objective of this issue is to make it possible for the user to request from the coverage backend a different revision than the latest.
> Right now we are always using the latest:
> 
> [code-coverage-reports/report.js](https://github.com/marco-c/code-coverage-reports/blob/51026a70697c1a78d571e3a2deca652f83419555/report.js#L68)
> 
> Line 68 in [51026a7](/marco-c/code-coverage-reports/commit/51026a70697c1a78d571e3a2deca652f83419555)
> 
>  const changeset = await get_latest(); 
> .

Thanks for the reply @marco-c .
I am a complete beginner.
I actually thought of adding a text-box in the header part, to search for any field.
I will revert back to you in no time after revising the files.
Can you please help me out with the step-wise process to approach to the right track of the issue?

**Comment by marco-c** [comment]
@dev503-student I've already explained everything in the issue. N.B.: The text box is needed, the user has to write the changeset in there, and the page will load it.
I will remove all the latest comments as they are confusing.

**Comment by dev503-student** [comment]
> @dev503-student I've already explained everything in the issue. N.B.: The text box is needed, the user has to write the changeset in there, and the page will load it.
> I will remove all the latest comments as they are confusing.

Ok Thanks for help! @marco-c

**Comment by ashutoshmishraji** [comment]
hi, @marco-c I want to contribute to this. Please guide me because this is my first time

**Comment by marco-c** [comment]
There is a description of what needs to be done in the issue itself.

**Comment by datavizard** [comment]
@marco-c , I was looking into this issue. I have a query, while we do have methods which currently hit the backend services for latest and file coverage, do we have a backend service which would take revision number as a parameter? I am not seeing any such service at https://coverage.testing.moz.tools/, there's one with phid revision, but you already mentioned above its unrelated. 
Hope, I made myself clear. I have the user submitted revision number from the search box but where exactly I am going to hit that revision at the backend to get those results?

**Comment by marco-c** [comment]
The API call is https://coverage.testing.moz.tools/ui/#!/legacy/codecoverage_backend_api_coverage_for_file, which we are already using.

Right now we always use the latest changeset, we have to allow the user to select one.

**Comment by datavizard** [comment]
@marco-c, at which IRC channel would you be available to talk to?

**Comment by marco-c** [comment]
#codecoverage

**Comment by vipulchhabra99** [comment]
hello @marco-c  i have created a pull request for same please review so that i can fix the bugs (if any).
